### PR TITLE
feat: add option to skip options validation

### LINKED ISSUE #264: Agent vails validation and cannot start if an alternative API endpoint is used
When setting an alternative API endpoint, eg to send events to Refinery, the agent always fails validation and does nor start. This is because the validation check attempts to lookup the API key and check it both exists and is valid.

### PR DESCRIPTION
**Pull request by JamieDanielson**
## Which problem is this PR solving?
When setting an alternative API endpoint, API key validation will fail and prevents the agent from starting. 

This PR adds a config option that will skip config validation if desired. 

- Closes #264 

## Short description of the changes

- Add configuration option `HONEYCOMB_SKIP_OPTIONS_VALIDATION` that, when set to True, skips the Validate function that today primarily does a lookup on the API Key in use.
- Move the Config Validate below the logging of config values; that way, if there is something wrong, the config values are printed out first for easier troubleshooting if it fails.

## How to verify that this has the expected result

Set a different `HONEYCOMB_API_ENDPOINT`.

With `HONEYCOMB_SKIP_OPTIONS_VALIDATION=false` (default), pod will fail to start and show an error in the logs after showing the provided configuration options.

```sh
2023-10-02 16:30:43 {"level":"fatal","error":"Invalid API key","time":"2023-10-02T20:30:43Z","message":"Config validation failed"}.
```
With `HONEYCOMB_SKIP_OPTIONS_VALIDATION=true`, no error will throw and agent will start up as expected. Data may not be sent if API Key doesn't match the endpoint but the pod will not get stuck in backoff.

```yaml
# deployment.yaml
...
            ## uncomment this to set the destination dataset for events
            - name: HONEYCOMB_API_ENDPOINT
              value: $HONEYCOMB_API_ENDPOINT
            ## uncomment this to skip options validation
            - name: HONEYCOMB_SKIP_OPTIONS_VALIDATION
              value: "$HONEYCOMB_SKIP_OPTIONS_VALIDATION"
```

### CODE REVIEW

**Review by MikeGoldsmith — COMMENTED** [review]
I think this is okay and could be useful in the future if/when we have more validation checks.

For now, I think a simpler solution would be to skip API key validation if the API endpoint is not the default value (eg `https://api.honeycomb.io`). This means we don't have to expose another config option which we already have lots of.

**Comment by JamieDanielson** [comment]
> skip API key validation if the API endpoint is not the default value (eg `https://api.honeycomb.io`). This means we don't have to expose another config option which we already have lots of.

I like this option! Will update.

**Comment by JamieDanielson** [comment]
Eh, I think it's easier to just open a new PR since this will be a totally different way to handle. Closing this.

**Comment by JamieDanielson** [comment]
Did the simpler option in #265

**Pull request closed without merging**
