### PR TITLE
maint: adding proper smoke test(s)

### LINKED ISSUE #78: Add basic smoke test

### PR DESCRIPTION
**Pull request by robbkidd**
## Which problem is this PR solving?

- Closes #78 

## Description of the changes

Set up a smoke test, details included in the new make targets below:
- `smokey_cluster_create`: Create kind cluster
- `smokey_collector_install`: Install collector via helm with new collector values, including a filter processor that only keeps echoserver spans from pods with a response code of 405
- `smokey_agent_install`: Install agent via helm with new agent values, including usage of a local image (installed if not available in the shell) and export to the collector
- `smokey_echo_job`: Install echoserver and run a job that sends a POST request expecting a 405 response
- `smokey_copy_output`: After a short wait, copy output from the newly created file saved with telemetry from collector
- `smokey_verify_output`: Make assertions via the new `verify.bats` bats test (similar to previous tests on other distros and in go auto-instrumentation) that the output contains the expected span and attributes
- `smoke`: Do all of the things above
- `unsmoke`: Tear it all down when done

Also updated PR, main, and release workflows to run the new smoke test.

## How to verify that this has the expected result

- Run `make smoke` and get a bunch of passing tests - also check out the (git ignored) json file that contains the remaining span that's being tested. `make unsmoke` to spin it down.

### CODE REVIEW

**Comment by JamieDanielson** [comment]
I've made a few changes, and can get telemetry to the collector and the file if I set the endpoint based on the IP address of the collector pod, but haven't yet figured out how to set it based on the name.

The latest change uses the helm chart again with a local image - that's currently commented out in Makefile but should probably be uncommented when this is ready to go so it builds in CI.

After running `make smoke`, if you adjust values in either of the files you can simply update with `helm upgrade smokey-agent honeycomb/network-agent --values smoke-tests/agent-helm-values.yaml` for agent and `helm upgrade smokey-collector open-telemetry/opentelemetry-collector -f smoke-tests/collector-helm-values.yaml` for collector. Add a `--dry-run` flag at the end of the command to see the full rendered output (also here is a [collector helm chart example](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector/examples/statefulset-only/rendered) for reference).

I also temporarily moved the `echoserver` stuff out of the smoke target for now while working on getting it to send to collector, because it was so noisy with local kube-system stuff anyway it didn't seem necessary to wait for the echoserver to spin up. With the current output it will be a pretty large file to work with for testing... but we may be able to get a decent test in with one of the liveness probe events. TBD.

**Comment by JamieDanielson** [comment]
Current state as of last push: running `make smoke` will successfully spin up the agent, spin up the collector, spin up the echoserver, run the smoke-job with a 404 (intentional) response, copy output from the collector log file, and run assertions on the trace using bats*.
Big * at the moment: I haven't yet been able to narrow down the test to only look at the echoserver spans. Because of this, the output is somewhat nondeterministic depending on how many health probes succeed while the thing is up. I've copied a resourceSpan for echoserver into a file `smoke-tests/traces-temp-test.json` so I could write the tests against it.

 ✓ Agent includes service.name in resource attributes
 ✓ Agent span includes custom resource attributes
 ✓ Agent emits a span name '{http.method}' (per semconv)
 ✓ Agent includes specified headers as attributes
 ✓ Agent includes k8s source attributes
 ✓ Agent includes k8s destination attributes
 ✓ HTTP span includes http.method attribute
 ✓ HTTP span includes http.target attribute
 ✓ HTTP span includes http.status_code attribute
 ✓ HTTP span includes client error attribute with 404 response
 ✓ Trace ID present in all spans
 ✓ Span ID present in all spans

12 tests, 0 failures

**Comment by JamieDanielson** [comment]
Note: I renamed the PR workflow job from docker-build to build-and-test, which seems to result in this "expected" status check that will never resolve. If that causes us problems I can revert that name change.

**Comment by robbkidd** [comment]
I'm not against. We'll need to update the branch protection rules for `main` to replace `docker-build` with `build-and-test`.

**Review by JamieDanielson — APPROVED** [review]
So because Robb opened this PR he can't approve it. I can approve it but uhh I'm a little biased as I picked it up and did the later work on it 😅 . I'm approving for the green checks - feel free to merge if y'all are good with it or let me know further feedback to be addressed!

**Review by MikeGoldsmith — APPROVED** [review]
We've all worked on this, so we can collectively approve & merge. Good work @robbkidd  and @JamieDanielson 🎉

**Pull request merged**
